import { expect, test } from '@playwright/test'

// Opt in explicitly. This test creates a match in the local demo database.
const base = process.env.GO_E2E_BASE_URL
const email = process.env.GO_E2E_EMAIL
const password = process.env.GO_E2E_PASSWORD

test('Go scoring: enter final scores directly and reject stale edits', async ({ page, context }) => {
	test.skip(!base || !email || !password, 'Requires the Go demo API and GO_E2E_* variables')
	test.setTimeout(120_000)
	expect(new URL(base!).hostname).toMatch(/^(localhost|127\.0\.0\.1)$/)
	const group = `${base}/en/tournaments/${process.env.GO_E2E_TOURNAMENT_ID || '1'}/groups/${process.env.GO_E2E_GROUP_ID || '1'}`
	const pageErrors: string[] = []
	page.on('pageerror', error => pageErrors.push(error.message))
	await page.goto(`${base}/en/auth/login`)
	await page.getByLabel('Email', { exact: true }).fill(email!)
	await page.getByLabel('Password', { exact: true }).fill(password!)
	const loginResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/login'))
	await page.locator('button[type="submit"]').click()
	expect((await loginResponse).status()).toBe(200)
	await page.waitForURL(url => !url.pathname.includes('/auth/login'))
	await page.goto(`${group}/addmatch`)
	await expect(page.getByRole('heading', { name: 'Add new match' })).toBeVisible()
	await page.locator('#player1_id').selectOption({ label: 'Alex' })
	await page.locator('#player2_id').selectOption({ label: 'Sam' })
	await page.locator('#set-0-player1_games').fill('6')
	await page.locator('#set-0-player2_games').fill('5')
	await page.locator('#set-1-player1_games').fill('6')
	await page.locator('#set-1-player2_games').fill('3')
	const invalid = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/api/v1/matches'))
	await page.getByRole('button', { name: 'Create match', exact: true }).click()
	expect((await invalid).status()).toBe(400)
	await expect(page.getByRole('alert').filter({ hasText: 'set 1 is unfinished' })).toBeVisible()
	await expect(page.locator('#set-0-player2_games')).toHaveValue('5')

	await page.locator('#set-0-player1_games').fill('7')
	await page.locator('#set-0-player2_games').fill('6')
	await expect(page.locator('#set-0-tiebreak_player1')).toHaveCount(0)
	await page.locator('#set-1-player1_games').fill('4')
	await page.locator('#set-1-player2_games').fill('6')
	await page.getByRole('button', { name: 'Add set' }).click()
	await page.locator('#set-2-player1_games').fill('10')
	await page.locator('#set-2-player2_games').fill('8')
	const saved = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/api/v1/matches'))
	await page.getByRole('button', { name: 'Create match', exact: true }).click()
	const savedResponse = await saved
	expect(savedResponse.status()).toBe(201)
	const result = await savedResponse.json()
	expect(result.version).toBe(1)
	await page.waitForURL(url => /\/groups\/\d+$/.test(url.pathname))
	await expect(page.getByText('Alex', { exact: true }).first()).toBeVisible()
	await page.getByRole('button', { name: 'Group table view', exact: true }).click()
	await expect(page.getByText('10', { exact: true }).first()).toBeVisible()
	await page.screenshot({ path: 'test-results/go-scoring-group.png', fullPage: true })

	const editURL = `${group}/${result.match_id}`
	await page.goto(editURL)
	await expect(page.locator('#set-0-player1_games')).toHaveValue('7')
	await expect(page.locator('#set-0-player2_games')).toHaveValue('6')
	await expect(page.locator('#set-2-player1_games')).toHaveValue('10')
	await expect(page.locator('#set-2-player2_games')).toHaveValue('8')
	const second = await context.newPage()
	await second.goto(editURL)
	await expect(second.locator('#set-2-player1_games')).toHaveValue('10')
	await page.locator('#set-2-player1_games').fill('11')
	await page.locator('#set-2-player2_games').fill('9')
	const updated = page.waitForResponse(response => response.request().method() === 'PUT')
	await page.getByRole('button', { name: 'Update match', exact: true }).click()
	expect((await updated).status()).toBe(200)
	await page.waitForURL(url => /\/groups\/\d+$/.test(url.pathname))

	await second.locator('#set-2-player1_games').fill('12')
	await second.locator('#set-2-player2_games').fill('10')
	const rejected = second.waitForResponse(response => response.request().method() === 'PUT')
	await second.getByRole('button', { name: 'Update match', exact: true }).click()
	expect((await rejected).status()).toBe(409)
	await expect(second.getByRole('alert').filter({ hasText: 'Another organizer changed this match' })).toBeVisible()
	await expect(second.locator('#set-2-player1_games')).toHaveValue('12')
	await second.getByRole('button', { name: 'Discard my edits and load latest result' }).click()
	await expect(second.locator('#set-2-player1_games')).toHaveValue('11')
	await expect(second.locator('#set-2-player2_games')).toHaveValue('9')
	await expect(second.getByRole('alert').filter({ hasText: 'Another organizer changed this match' })).toHaveCount(0)
	await second.close()
	expect(pageErrors).toEqual([])
})
